import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { LoginButton } from "@/components/LoginButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 bg-opacity-40 min-h-screen`}>
        <header className="flex justify-between items-center py-3 rounded-md mt-4 bg-white md:px-10 max-w-6xl mx-auto shadow-md shadow-gray-100">
          <Link href={"/"} className="text-lg text-center font-bold">
            TRAVIS P.A.
          </Link>
          <LoginButton>Login</LoginButton>
        </header>
        <main className="max-w-6xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
